### ISSUE TITLE
输入用户名和密码，提示404

### ISSUE THREAD

**Issue by ludashi2020** [moeakwak/chatgpt-web-share#18]
![WeChat截图_20230320114153.png](https://pic.shenbian.tv/2023/03/20/db11dae0a5e82.png)

**Comment by moeakwak** [comment]
你是不是没用docker部署呢？

感觉可能是反向代理路径不对



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月20日 11:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [moeakwak/chatgpt-web-share] 输入用户名和密码，提示404 (Issue #18) |

**Comment by ludashi2020** [comment]
> 你是不是没用docker部署呢？ 感觉可能是反向代理路径不对
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年03月20日 11:43 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***> | | 主题 | [moeakwak/chatgpt-web-share] 输入用户名和密码，提示404 (Issue #18) | — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

我没有使用docker部署，前端build静态化文件了,使用了nginx反代
`   location /api {
    proxy_pass http://127.0.0.1:8000;
  }
  
    location / {
    root /home/wwwroot/chatgpt-web-share/frontend/dist;
    try_files $uri $uri/ /index.html;
    index index.html;
  }`

**Comment by moeakwak** [comment]
你需要rewrite路径，把/api去掉。后端url里面没有/api



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月20日 11:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [moeakwak/chatgpt-web-share] 输入用户名和密码，提示404 (Issue #18) |

你是不是没用docker部署呢？ 感觉可能是反向代理路径不对
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年03月20日 11:43 | | 收件人 | @.> | | 抄送至 | @.> | | 主题 | [moeakwak/chatgpt-web-share] 输入用户名和密码，提示404 (Issue #18) | — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>

我没有使用docker部署，前端build静态化文件了,使用了nginx反代
` location /api {
proxy_pass http://127.0.0.1:8000;
}

location / {
root /home/wwwroot/chatgpt-web-share/frontend/dist;
try_files $uri $uri/ /index.html;
index index.html;


}`

**Comment by ludashi2020** [comment]
> 你需要rewrite路径，把/api去掉。后端url里面没有/api
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年03月20日 11:54 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [moeakwak/chatgpt-web-share] 输入用户名和密码，提示404 (Issue #18) | 你是不是没用docker部署呢？ 感觉可能是反向代理路径不对 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年03月20日 11:43 | | 收件人 | @.> | | 抄送至 | @.> | | 主题 | [moeakwak/chatgpt-web-share] 输入用户名和密码，提示404 (Issue #18) | — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 我没有使用docker部署，前端build静态化文件了,使用了nginx反代 ` location /api { proxy_pass http://127.0.0.1:8000; } location / { root /home/wwwroot/chatgpt-web-share/frontend/dist; try_files $uri $uri/ /index.html; index index.html; }` — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

我去掉了这段 ```
location /api {
    proxy_pass http://127.0.0.1:8000;
  }
```
只保留了  ```
location / {
    root /home/wwwroot/chatgpt-web-share/frontend/dist;
    try_files $uri $uri/ /index.html;
    index index.html;
  } 
```
现在登录，报405错误了![WeChat截图_20230320120316.png](https://pic.shenbian.tv/2023/03/20/e8d0e5efcd09e.png)

**Comment by moeakwak** [comment]
你的nginx配置显然是不对的。

如果你对nginx不熟悉，建议使用caddy，我有提供caddy的配置。或者，你可以让chatgpt帮你转写caddyfile到nginx的配置。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月20日 12:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [moeakwak/chatgpt-web-share] 输入用户名和密码，提示404 (Issue #18) |

你需要rewrite路径，把/api去掉。后端url里面没有/api
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年03月20日 11:54 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [moeakwak/chatgpt-web-share] 输入用户名和密码，提示404 (Issue #18) | 你是不是没用docker部署呢？ 感觉可能是反向代理路径不对 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年03月20日 11:43 | | 收件人 | @.> | | 抄送至 | @.> | | 主题 | [moeakwak/chatgpt-web-share] 输入用户名和密码，提示404 (Issue #18) | — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 我没有使用docker部署，前端build静态化文件了,使用了nginx反代 location /api { proxy_pass http://127.0.0.1:8000; } location / { root /home/wwwroot/chatgpt-web-share/frontend/dist; try_files $uri $uri/ /index.html; index index.html; } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***>

我去掉了这段 ```
location /api {
proxy_pass http://127.0.0.1:8000;
}

只保留了  ```
location / {
    root /home/wwwroot/chatgpt-web-share/frontend/dist;
    try_files $uri $uri/ /index.html;
    index index.html;
  } 


现在登录，报405错误了

**Comment by ludashi2020** [comment]
> 你的nginx配置显然是不对的。 如果你对nginx不熟悉，建议使用caddy，我有提供caddy的配置。或者，你可以让chatgpt帮你转写caddyfile到nginx的配置。
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年03月20日 12:05 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [moeakwak/chatgpt-web-share] 输入用户名和密码，提示404 (Issue #18) | 你需要rewrite路径，把/api去掉。后端url里面没有/api … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年03月20日 11:54 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [moeakwak/chatgpt-web-share] 输入用户名和密码，提示404 (Issue #18) | 你是不是没用docker部署呢？ 感觉可能是反向代理路径不对 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年03月20日 11:43 | | 收件人 | @.> | | 抄送至 | @.> | | 主题 | [moeakwak/chatgpt-web-share] 输入用户名和密码，提示404 (Issue #18) | — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 我没有使用docker部署，前端build静态化文件了,使用了nginx反代 location /api { proxy_pass http://127.0.0.1:8000; } location / { root /home/wwwroot/chatgpt-web-share/frontend/dist; try_files $uri $uri/ /index.html; index index.html; } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***> 我去掉了这段 ``` location /api { proxy_pass http://127.0.0.1:8000; } 只保留了 ``` location / { root /home/wwwroot/chatgpt-web-share/frontend/dist; try_files $uri $uri/ /index.html; index index.html; } 现在登录，报405错误了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

nginx配置搞定了，现在登录进去回复，出现了1006错误
![WeChat截图_20230320121236.png](https://pic.shenbian.tv/2023/03/20/4aa961c6d2fa1.png)
config.yaml配置如下：![WeChat截图_20230320121423.png](https://pic.shenbian.tv/2023/03/20/8fb9faae05f59.png)

**Comment by ludashi2020** [comment]
> 你的nginx配置显然是不对的。 如果你对nginx不熟悉，建议使用caddy，我有提供caddy的配置。或者，你可以让chatgpt帮你转写caddyfile到nginx的配置。
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年03月20日 12:05 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [moeakwak/chatgpt-web-share] 输入用户名和密码，提示404 (Issue #18) | 你需要rewrite路径，把/api去掉。后端url里面没有/api … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年03月20日 11:54 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [moeakwak/chatgpt-web-share] 输入用户名和密码，提示404 (Issue #18) | 你是不是没用docker部署呢？ 感觉可能是反向代理路径不对 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年03月20日 11:43 | | 收件人 | @.> | | 抄送至 | @.> | | 主题 | [moeakwak/chatgpt-web-share] 输入用户名和密码，提示404 (Issue #18) | — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 我没有使用docker部署，前端build静态化文件了,使用了nginx反代 location /api { proxy_pass http://127.0.0.1:8000; } location / { root /home/wwwroot/chatgpt-web-share/frontend/dist; try_files $uri $uri/ /index.html; index index.html; } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***> 我去掉了这段 ``` location /api { proxy_pass http://127.0.0.1:8000; } 只保留了 ``` location / { root /home/wwwroot/chatgpt-web-share/frontend/dist; try_files $uri $uri/ /index.html; index index.html; } 现在登录，报405错误了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

已经搞定了。谢谢。

**Comment by itcuihao** [comment]
> nginx不熟悉，建议使用caddy，我有提供caddy的配置。或者，你可以让chatgpt帮你转写caddyfile到nginx的配置。
> […](#)

分享份完整的nginx配置吧，我看所有的文档都是零零散散的
